### ISSUE TITLE
Island data is not stored with the world, won't be backed up

### ISSUE THREAD

**Issue by LoyLT** [TheCricket/FTB-Islands#10]
Island data is currently being stored in the \local directory instead of \world

the island data is meaningful only to the current world,.. so like all other data that changes with the world, it should be inside the world's directory....  

also... **the most common backup systems are only backing up the folder for the world data.... so what happens if they lose their island data and have no backup?**

however... don't just hardcode it to \world.....  someone may have changed their server so the world data they're playing on is in a different folder than world, by editing the "level-name" value in the server.properties file... so you really need to store the island data in whatever folder that value is pointing to

**Comment by sitedyno** [comment]
Yes. /island join broke for me after upgrade and this is why. I had no idea that I needed to copy the local/ directory along with the world/ directory to the new server instance. Please store data relevant to the world in the world/ directory.

**Comment by TheCricket** [comment]
I've heard this so many times

**Comment by TheCricket** [comment]
sitedyno your local directory should never be moved when updating. Its for things that will never change. So all the server config files go there. Thats why I put it there

**Comment by ZeekDaGeek** [comment]
My island storage file was just corrupted and now I have no backup of the island file seeing as it's all stored in some silly /local/ folder which is pretty infuriating.

**Comment by kolatra** [comment]
I can still do this, however I'm scared to because of people's already existing data.

**Comment by sitedyno** [comment]
I suppose it's a bit moot for 1.7.10. If you plan to update for 1.10 etc I would implement it there. Just my 2 cents :)

**Comment by kolatra** [comment]
1.10.2 isn't happening at this point, so I shall close this. If that changes I will reopen and implement this.
