### ISSUE TITLE
Suggestion: Place the User via the center of regions rather then on the border of 4 regions.

### ISSUE THREAD

**Issue by StoneLegion** [TheCricket/FTB-Islands#12]
This one is a tough one maybe something admins can enable via a config overtime. But overall placing the user on 1k and 1k is a very very bad idea. Because this means the users on the border of 4 regions. Not only it means you have to worry about 4 more files per user it also means that if someone busts 1 region you can't nuke it without taking out say 1/4 of another persons base.

I would Highly recommend changing it so it's in the center of each region and add a config option to enable this setting as it be a mess to force current servers to this method.

**Comment by TheCricket** [comment]
Thats already how it works

**Comment by LoyLT** [comment]
0,0 is not the center of a region file
