### ISSUE TITLE
Needed Commands

### ISSUE THREAD

**Issue by DrZed** [TheCricket/FTB-Islands#14]
Properly list your stuff...
Also have /island help, /island list (option to have islands public), /island name (if you forgot your island's name), /island disown/destroy (admin command)
Commands added

**Comment by TheCricket** [comment]
I don't know what this means....

**Comment by kolatra** [comment]
Well, we already have the disown command, that's in the latest release.

**Comment by DrZed** [comment]
Well, I forgot what I named my island so I can't tell a friend to /island join
Add a /island name...
As for localizing your command it does "island <text>" when /help island
For /island list have it an optional command to list islands (not that hard since you're using a hashmap)
Just push the keys into chat (make it an admin command if must)
I was Tired as hell since i was recoding my mods when I originally made this issue report.
In the end I just tp'd him to me and he can break blocks and stuff so it's no big deal.
(Idea since islands appear to be 1000x1000 save the x,z and then in player interact event just cancel if player isn't part of the island (I do it for my protection command (WIP)))

**Comment by DrZed** [comment]
lol I didn't notice this was still open. I even forgot I opened it.
