### ISSUE TITLE
Cannot create or Join Island on 1 user

### ISSUE THREAD

**Issue by willierpt** [TheCricket/FTB-Islands#15]
A few people have joined and everything worked great, untill one of our players ran into this issue:
`06.04 11:12:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
06.04 11:12:13 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
06.04 11:12:13 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1324) [nh.class:?]
06.04 11:12:13 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchVanillaCommand(CraftServer.java:733) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
06.04 11:12:13 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:53) [CraftSimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
06.04 11:12:13 [Server] INFO at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [z.class:?]
06.04 11:12:13 [Server] INFO at com.cricketcraft.ftbisland.SpawnIslandCommand.func_71515_b(SpawnIslandCommand.java:67) ~[SpawnIslandCommand.class:?]
06.04 11:12:13 [Server] INFO at com.cricketcraft.ftbisland.IslandCreator.joinIsland(IslandCreator.java:72) ~[IslandCreator.class:?]
06.04 11:12:13 [Server] INFO java.lang.NullPointerException
06.04 11:12:13 [Server] ERROR Couldn't process command: 'island join Yomigaere'`

She cannot Join an island, and im not sure the island is created since there is no feedback from the command.
We are running with KCauldron

The log is from bottom to top :)

**Comment by willierpt** [comment]
Problem is fixed in your update to 1.1.1.
Please Close

**Comment by kolatra** [comment]
For future reference, you can close your own issues if you feel they are resolved. :)

**Comment by willierpt** [comment]
Alright Thanks :)
