### ISSUE TITLE
Not required on client side, ExCompressum not needed, missing LICENSE

### ISSUE THREAD

**Issue by ZeekDaGeek** [TheCricket/FTB-Islands#16]
At the moment you currently have it so the version must match on the client side, which seems odd for a server side mod. This is very important so we can implement things like the command block changes without requiring the whole modpack to be updated:

```
@Mod(modid = FTBIslands.MODID, name = FTBIslands.NAME, version = FTBIslands.VERSION, acceptableRemoteVersions = "*")
```

Also ExCompressum isn't needed as an include.

IslandCreator.java

```
-import net.blay09.mods.excompressum.ModItems;
+import cpw.mods.fml.common.registry.GameRegistry;

...

-            chest.setInventorySlotContents(10, new ItemStack(ModItems.chickenStick, 1));
+            Item chickenStick = GameRegistry.findItem("excompressum", "chickenStick");
+
+            if (chickenStick != null) {
+                chest.setInventorySlotContents(10, new ItemStack(chickenStick, 1));
+            }
```

Also missing LICENSE, example: https://github.com/PC-Logix/OpenPrinter/blob/1.7/LICENSE

**Comment by TheCricket** [comment]
This should be in the pack update soon. I had all this but I was a bit rushed

**Comment by kolatra** [comment]
I've just settled the ExCompressum dependency issue, and the license will have to be Cricket's decision.

**Comment by kolatra** [comment]
This is fixed now.
