### ISSUE TITLE
Island Limit

### ISSUE THREAD

**Issue by zlyfire** [TheCricket/FTB-Islands#21]
Why is the limit of islands set to 100? I don't run a server, but I have tried looking at my own instance to see if that was changeable, but I didn't see anything. So would it be possible to up the limit, or have it changeable in the configs?
I ask because servers, esp those that don't run on a whitelist, can get lots of unique players, most of whom would probably make their own island and fill 100 up very fast. Most server owners that would anticipate that ignore this mod entirely and get a skyblock plugin, which ends up breaking all forms of dimension travel back (returning from another dimension, but expects the overworld leads to spawning in the void with those plugins since they use their own dimension).
So, to repeat the question as a TLDR: would it be possible to increase the amount of islands a server can generate?

**Comment by kolatra** [comment]
With the way the math works for the islands, the maximum is actually supposed to be 398. Are you actually having issues with generating over 100?

**Comment by phit** [comment]
we at stonebound.net just ran into the limit, when i now do /island create <name> it starts cycling coords from the beginning

according to a search I did on all server logs we didn't even create a 100 islands, apparently /island setspawn counts towards the 100 too
you can find the data here https://stonebound.net/files/islands/

**Comment by TheCricket** [comment]
You didn't hit the limit The limit is 398

**Comment by phit** [comment]
then explain to me why new islands loop from the spawn again? if you don't believe me I can send you the .ser file and you can try it yourself

**Comment by TheCricket** [comment]
I mean you really shouldn't be running a server when you have that many islands going. I am struggling on computing power with 20ish average late game players

**Comment by zlyfire** [comment]
Kolatra,
As I said I do not run a server. I'm just asking why the limit is 100 (or 398, should be updated on curse and such). That number is "low" for server owners that I know, so they instead use other plugins rather than this mod.
From what I understand, this mod uses the over world for the islands, whereas the plugins tend to use their own dimension, which breaks things as I've said.

**Comment by TheCricket** [comment]
zlyfire, Read my comment :P

**Comment by kolatra** [comment]
Would either of you be opposed to a simple config option? That way it can be adjusted to fit a server's needs.

**Comment by TheCricket** [comment]
I don't think anyone is opposed to a choice :dancer:

**Comment by zlyfire** [comment]
Excellent!
