### ISSUE TITLE
Unable to join custom named islands

### ISSUE THREAD

**Issue by esvinson** [TheCricket/FTB-Islands#22]
Version 1.2.0
Islands that are created with a custom name that isn't a players name are not join-able, as you aren't friends with the 'player'.

**Comment by kolatra** [comment]
Ah yeah, I probably shouldn't have assumed that all islands names are gonna be player names. I'll fix it.

**Comment by TheCricket** [comment]
This doesn't really fix the error, I would just add an optional <player> at the end of creation for custom named islands
