### ISSUE TITLE
World is not true void.. 

### ISSUE THREAD

**Issue by MrSapient** [TheCricket/FTB-Islands#28]
So i got a Jetpack today and started flying around to find massive parts of normal land..

http://i.imgur.com/k4vBqkL.png

Any idea why ?

PACK.. FTBInfinityEvolvedSkyblock-1.1.0-1.7.10
Also this is on a server.

Is there anyway to make it a void with out losing all my work?

**Comment by James137137** [comment]
could you remove them chunks via deleting the region files? has anyone made islands above those regions?

**Comment by TheCricket** [comment]
This has nothing to do with FTB Islands
