### ISSUE TITLE
Commands not compatible with Cauldron

### ISSUE THREAD

**Issue by phit** [TheCricket/FTB-Islands#3]
since you basically just implement one command it's impossible to just give the permission to create islands to players
Would be nice if you could split the join and create command

`[16:09:29] [Server thread/INFO]: Registered command island with permission node com.cricketcraft.ftbisland.SpawnIslandCommand`

**Comment by kolatra** [comment]
Sorry, we don't support Cauldron.

**Comment by willierpt** [comment]
It's really hard to create everyone's island with that awnser. But that's your call.

**Comment by TheCricket** [comment]
If you are running a cauldron server you are doing it wrong in the first place
