### ISSUE TITLE
Bug: Creating new islands overwriting existing islands

### ISSUE THREAD

**Issue by chrysillis** [TheCricket/FTB-Islands#30]
I'm having trouble creating more than 2-3 islands. I've also confirmed this issue is happening on the version packaged with FTB Infinity Evolved Skyblock and the latest version posted on curse.

In FTB, I type /island create <insert name> and no problem. Makes an island. I do it again. Again makes an island. I do it again. It says I made a new island, but teleporting to that new island it turned out to be Island 1 instead of Island 3. It's overwriting the islands. I tried it multiple times to confirm it keeps happening. So right now, I can't make more than 2-3 unique islands. One time I got it to make 3 islands, but then the 4th was actually the 1st again.

Also, is there a way to manually specify where a new island will be generated? We wanted to make the islands close to each other to build bridges between them.

**Comment by TheCricket** [comment]
Because its taking your username by default if you don't give it a name. Meaning you are using the same name every single time. This is not a bug, this is user error
