### ISSUE TITLE
/island_create overwrites other islands,

### ISSUE THREAD

**Issue by SteseDav** [TheCricket/FTB-Islands#31]
/island_create overwrites other islands even if you specify the island name. 

This is showing up in my infinity evolved expert skyblock 1.2.0 (MC Ver 1.7.10).

`{"freelandia":{"x":1000,"y":60,"z":-1000},"test":{"x":1000,"y":60,"z":-1000},"wonderland":{"x":2000,"y":60,"z":2000},"Isabella":{"x":-1000,"y":60,"z":-1000},"Spawn":{"x":0,"y":60,"z":0}}`

is my current islands.json file. 

I created the islands in the following order : - 

Spawn (created at world gen)
Isabella
test (overwrote Isabella's blocks, then deleted)
test (left in situ, to allow next island)
freelandia
test (dropped over freelandia, but not yet deleted)
wonderland

Is this an issue with the ordering in the file? The server is running on a different machine to the one that did the world gen. Spawn and Isabella were created on the same machine, the server folder then was moved, and the others were created. 

hope this helps with diagnosis.

**Comment by kolatra** [comment]
This is... Odd? I'll look into it.

**Comment by kolatra** [comment]
Can't reproduce. Using island_create will always use a free position. 

![Image](http://i.imgur.com/vDRcV9W.png)

**Comment by kolatra** [comment]
Any more information on this?

**Comment by SteseDav** [comment]
Sorry for the slow reply, I didn't have email notifications on... D'oh. 

The only info I can add is that I moved the server from one machine to another... which I suspect has caused the issue, but I can't fathom out why, unless the code has another record of the spaces used, other than the .json file.

Question :- in your test, does your island.json look like mine?

**Comment by kolatra** [comment]
I created the islands in the same order that you gave in the original issue, and the island.json does not look like yours. It added to it in the order that I created the islands, and removed the proper ones when I used the remove command.

This is definitely an odd issue, but I suspect it may have been an edge case kind of problem.

**Comment by SteseDav** [comment]
Hi, 

I figured that the json wouldn't match, and I think that is the cause of the over write issue. 

I really should look at the code, and answer this for myself but... Does the code use anywhere else to work out where to put islands, other than the Json?

**Comment by kolatra** [comment]
The code decides where to put the islands based on a list of positions that is created on launch, the json simply stores where the islands are so that the used up areas are not reused even after a launch.

**Comment by SteseDav** [comment]
Hmm, strange mine should over write then... i'll leave it in your hands if you want to continue investigating or not, as so far i'm the only one reporting the issue, I'd guess you'd close it, as you can't reproduce.

Thanks for the help.
