### ISSUE TITLE
Unable to compile FTB-Islands.

### ISSUE THREAD

**Issue by epilimic** [TheCricket/FTB-Islands#32]
Hello, I noticed that there was a lack of config for how far the islands are created, and I'd like them smaller. I found where in the code it is that has the hardcoded distance of 1000 blocks. Well before I go into changing it and whatnot I'm trying to simply compile the mod as-is. Unfortunately I'm running into this issue and I'm not sure what I need to do from here.

C:\Users\box\Desktop\FTB-Islands-master\FTB-Islands-master\build\sources\java\com\cricketcraft\ftbisland\commands\JoinIslandCommand.java:50: error: cannot find
symbol
        return MinecraftServer.getServer().getAllUsernames();
               ^
  symbol:   variable MinecraftServer
  location: class JoinIslandCommand

Here's a log from trying to compile: http://pastebin.com/DsubdZGj
Here's one with the --stacktrace option: http://pastebin.com/vUHarWSG

I do see that message about -Xlint:unchecked but I couldn't figure out how to set it. None of the options listed on this thread at stackoverflow worked. http://stackoverflow.com/questions/8215781/how-do-i-compile-with-xlintunchecked

Any help on this would be greatly appreciated. I would love to get some islands going for a small community server but we don't want to be so far apart from each other. Thanks!

**Comment by TheCricket** [comment]
well if you modified it, and you can't compile it. Then that is your fault

**Comment by Kolatra** [comment]
If you want the mod for a small community server, download it from Curse.

**Comment by kolatra** [comment]
They didn't modify it yet, Master is missing an import that happened from a PR that I merged.
