### ISSUE TITLE
Why did you close my other report without reading it?

### ISSUE THREAD

**Issue by epilimic** [TheCricket/FTB-Islands#33]
I clearly stated in my issue that I was trying to compile the mod as-is WITHOUT CHANGING ANYTHING first. I haven't changed a single thing. I'm simply trying to compile it without ANY changes. Please re-read my issue... really rude to close it on me under the assumption that I've made changes when I haven't changed a thing.

**Comment by TheCricket** [comment]
I read it

**Comment by epilimic** [comment]
So then why did you reply "well if you modified it, and you can't compile it. Then that is your fault" when I clearly said that I did NOT modify it? 

I mean if you guys are actively refusing to help compile your plugin out of the box then that's one thing, but to brush me off as if I've changed something when I've done nothing of the sort is pretty shitty of you.

All I did was clone the repo and your mod does not compile. I've tried on windows and linux with the exact same result.
