### ISSUE TITLE
Command Blocks compatibility

### ISSUE THREAD

**Issue by meza** [TheCricket/FTB-Islands#34]
Hi,

I'm trying to create a small lobby for my server, where new players can get their new islands and settle in. Unfortunately neither of the commands seem to work from within a command block, due to permission issues. Also, a "create, setspawn and join" single command (like `/island_init <islandName> <playerName>` would be so nice for server admins, which command would simply tp players to their islands if it's pressed for the 2nd+ time by the same user.

**Comment by kolatra** [comment]
I'm not too sure about the "init" command. 

I'll play around with the idea, but I have implemented the command block compatibility.

**Comment by kolatra** [comment]
Closing as command blocks are usable now.

**Comment by meza** [comment]
Amazing, will test it out shortly!

**Comment by Gunner76th** [comment]
I see where you stated that command blocks are now usable, however in version 1.3.1 that is on Curse as the most recent release, and is included with SkyFatory 2.5, I am unable to use command blocks to execute /island_create. I have opened a new issue tracker https://github.com/Kolatra/FTB-Islands/issues/38 regarding this. Was this functionality added but a release not compiled and pushed to Curse for download?
