### ISSUE TITLE
Source in master does not compile

### ISSUE THREAD

**Issue by exaskye** [TheCricket/FTB-Islands#35]
There is a missing import for MinecraftServer in [JoinIslandCommand](https://github.com/Kolatra/FTB-Islands/blob/master/src/main/java/com/cricketcraft/ftbisland/commands/JoinIslandCommand.java).

Introduced in 8aedf1b0. Not present in the 1.10.2 port due to [this change](https://github.com/Kolatra/FTB-Islands/commit/8c9ee4ed9a0444c236e2dec44e890d963d1d85e1#diff-c96e057c1954c56951854fb19917dd1cR13).

Related: #32

**Comment by kolatra** [comment]
Oh I think I know why this happened, the person who did the PR edited it on GitHub so it didn't add the import. Thanks for letting me know about this.

I should have noticed it before merging, but I was in a rush and let it slip past.
