### ISSUE TITLE
License Issues

### ISSUE THREAD

**Issue by asiekierka** [TheCricket/FTB-Islands#36]
I'd like to report that your license is very flawed in ways which are technical rather than personal:
- 1d: "including, without limitation, performance, broadcast, sound recording, and Sui Generis Database Rights"

Was this copy-pasted from sound-related material? You might want to list things which actually pertain to software instead. The MIT License uses "including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software".
- 1d: "Copyright and Similar Rights"

That term is not actually used anywhere else, making the definition useless. You probably meant to use it in 1e, where you used "Licensed Rights" instead.
- 2b: "You may not copy code for use in your own codebase."

Can you copy code for use in someone else's codebase, though?
- 2c: "Adapted Material such as addon mods"

"Addon mods" is not defined anywhere, and is very arbitrary.
- 2c: "Adapted Material such as addon mods is encouraged. All other works should be discussed with the Owner"

Section 1c already says that you have to get permission for any adapted material with the Owner - "or otherwise modified in a manner requiring permission from the Owner". Also, "discussed" is vague.
- 2d: "You may not reupload the mod as a download."

Can I reupload it in different forms? For example, I could put up a Magnet link for a torrent file to download the mod - that way, nobody reuploads the entire mod as a download.
- 2d: "You may not reupload the mod as a download."

"the mod" is vague. Can I reupload the source code? Just parts of the mod? Can I split the mod in two, or remove a few langfiles?
- 2d: "You will be confronted with a DMCA notice if found."

"DMCA" is too specific for a license - it effectively limits what you can do when the point is violated to sending a DMCA notice, and some countries (China, Russia) do not respect them very much.

Additionally,
- The license in general doesn't cover edge-cases related to art or language: for instance, it does say you can view the code and art, but not the langfiles (however, this section is null and void within the context of GitHub, as GitHub gives you explicit rights to view and fork the source code within the UI of their own website in the ToS).

Writing licenses is hard. Please don't write terrible licenses next time. (Personally, I'd prefer you just use a FOSS license, but that is probably unlikely judging by the restrictions you put on your users.)

**Comment by asiekierka** [comment]
Discussed and solved outside of the GitHub issue - for context of what happened here, read through the issue changes above this comment (also keep in mind that the body of the issue was voided).

**Comment by kolatra** [comment]
Issue will be open until I decide on a new license for the project.
