### ISSUE TITLE
Command block issue, part 2

### ISSUE THREAD

**Issue by Gunner76th** [TheCricket/FTB-Islands#39]
Ok so yay that we have fixed the permissions problem with command blocks. Now, when I enter the command into the block "/island_create @p" and then in another one "/island_join @p" the first command block has in its Previous Output "/island_create @p" and when I do "/island_join @p" it outputs "Please specify which player you wish to perform this action on." 

I am new to using command blocks, so I am sure I am missing something in this process. What I am setting up is 1 command block that when activated, will create an island named after the player in the database. IE If JimBob pushes the button for the command block with the command /island_create @p then it will create an island named JimBob. I then want to setup a second command block that will join player JimBob to island JimBob when he pushes the button. 

As an admin, if I was on the command console, or even in game on the console, how would I go about targeting another player with the /island_join command instead of it affecting myself directly? And how would I go about having the command /island_create use the @p which is suppose to pull the name of the closest player and use that as the input of the command?

**Comment by kolatra** [comment]
The join command outputting that message is because of me using *getCommandSenderAsPlayer(player)* in the code for that specific command, which checks if the sender is a player specifically rather than the console or even a command block.

I can look into a possible way of fixing it tomorrow, it's rather late.

**Comment by kolatra** [comment]
This was actually a simple fix. In my testing with command blocks, /island_create @p works perfectly, and I have fixed /island_join @p to join that island.

**Comment by cryptiklemur** [comment]
Seems like `/island_create @p` creates an island with the name of literally `@p`
