### ISSUE TITLE
FEATURE REQUEST: Custom Islands

### ISSUE THREAD

**Issue by jelaw21** [TheCricket/FTB-Islands#42]
I saw in the config there are 4 ready-made islands. Is there a way to create your own custom schematics to use instead of the ones provided?

**Comment by TheCricket** [comment]
yep, just build a custom version of the mod

**Comment by jelaw21** [comment]
Umm...how?

**Comment by Kolatra** [comment]
There is not a way, and it is not planned whatsoever.
